### ISSUE TITLE
Repeat Question Logic

### ISSUE THREAD

**Issue by gilpasternak35** [lei-ucsd/ai-tutor-cse8a-client#12]
Reforming the client:

The client will now take in a dictionary of questions, to be generated once for each stage (remember, understand, apply, analyze). This will be called questions. 

Then it can pass these questions into the endpoint every time, which will implement the logic of whether or not to retry a question when returning the response. The endpoint will decide to move on to the next question or regenerate on the basis of numCorrect.

**Comment by rlisahuang** [comment]
new field: `questions`

**Comment by rlisahuang** [comment]
complete in #14
